### ISSUE TITLE
replica set urls don't work.

### ISSUE THREAD

**Issue by stephen-fanfair** [jugglingdb/mongodb-adapter#25]
The standard replica set urls provided by most hosted mongodb providers don't work. They follow a structure like `mongodb://user:password@host:port,host:port/db`. They work fine when using mongo.connect directly, so I'd consider this a bug.

**Comment by Fcena** [comment]
Hi all,

Any update for this issue ?

Kind regards

**Comment by Fcena** [comment]
@stephen-fanfair have you found a workaround for this ? 

Regards

**Comment by 1602** [comment]
Hi @Fcena I suspect update of mongodb package might help, but i need test case to confirm.

**Comment by 1602** [comment]
@Fcena I've just updated this package to work with latest mongodb and tests passed on node 4, 5, 6

Let me know if this is resolves your issue.

**Comment by Fcena** [comment]
Hi @1602  I've tried this with your changes and still not working,
Have you tried with a URL like this ?
`"mongodb://kay:myRealPassword@mycluster0-shard-00-00-wpeiv.mongodb.net:27017,mycluster0-shard-00-01-wpeiv.mongodb.net:27017,mycluster0-shard-00-02-wpeiv.mongodb.net:27017/admin?replicaSet=Mycluster0-shard-0&ssl=true";`

Regards

**Comment by 1602** [comment]
@Fcena have you specified `{ rs: true }` in your schema settings?

**Comment by Fcena** [comment]
@1602 I have passed 
```
{
"url" : "mongodb://kay:myRealPassword@mycluster0-shard-00-00-wpeiv.mongodb.net:27017/admin?ssl=true,mongodb://kay:myRealPassword@mycluster0-shard-00-01-wpeiv.mongodb.net:27017/admin?ssl=true,mongodb://kay:myRealPassword@mycluster0-shard-00-02-wpeiv.mongodb.net:27017/admin?ssl=true",
"rs" : "NAME_OF_REPLICASET" 
}
```
And receive a error:

Unhandled error: TypeError: mongodb.ReplSetServers is not a function
    at new MongoDB (c:\GIT\xportercloud\node_modules\jugglingdb-mongodb\lib\mongodb.js:79:18)
    at Object.initializeSchema [as initialize] (c:\GIT\xportercloud\node_modules\jugglingdb-mongodb\lib\mongodb.js:58:22)
    at new Schema (c:\GIT\xportercloud\node_modules\jugglingdb\lib\schema.js:105:13)

What im trying to do is able juggling-mongodb to connect to a replicaSet using a URI like described [here](https://docs.atlas.mongodb.com/driver-connection/#node-js-driver-example)

Regards

**Comment by 1602** [comment]
Confirmed, this is not a function anymore. I pushed updated code to master just now. Let me know if this is resolves a problem. Unfortunately this functionality is not covered with tests.

**Comment by Fcena** [comment]
Hi @1602 , is not working yet, it returns "Process finished with exit code 1" what is also happening in my fork of mongodb-adapter. I'm trying to figure it out but without success until now..

**Comment by Fcena** [comment]
@1602 , That was a mistake in my code, is all working fine now :) 
Regards

**Comment by 1602** [comment]
Yey!

**Comment by Fcena** [comment]
Im using my fork but both work :)

**Comment by 1602** [comment]
@Fcena which node version are you using by the way (i'm considering to stick with latest node for next major jugglingdb release and all adapters)

**Comment by Fcena** [comment]
@1602 Im using 4.4.3 in production and 5.6.0 in dev, but in future I will update both to v6

**Comment by Fcena** [comment]
Hi @1602,

I have created a pull request in order to enable mongodb-adapter using the new connection api for replicaSets. 

Best Regards
