### ISSUE TITLE
Array in Jugglingdb schema has some weird side effects

### ISSUE THREAD

**Issue by bryanrasmussen** [jugglingdb/mongodb-adapter#31]
Sorry for the bad description, but hard to make a succinct one that would really clarify the problem. 

I have the following schema 

var ImageMappingWidget = describe("ImageMappingWidget", function () {
    property("schema_version", Number, {default: schema_version});
    property("has_hotspots", Boolean, {default: false})
    property("name", String);
    property("image", String);
    property("width", String);
    property("height", String);
    property("inlinehotspots", Array);
    property("createDate", Date, {default: function () { return new Date;}} );
    property("updateDate", Date, {default: function () { return new Date;}} );
    property("uploadedImage", Boolean, {default:false});
    property("requiredWidth", String);
    set("restPath", pathTo.imageMappingWidgets);
});
Then in my code somewhere I do the following (took out a bunch of code, this just shows the core)

var updatehotspots = [];
 var thishotspot = {
                      x : rawHotspot.x,
                      y : rawHotspot.y,
                      product : product

                  };
updatehotspots.push(thishotspot);

 var updating = {
         name: name,
         updateDate: Date.now(),
         has_hotspots: true,
         inlinehotspots: updatehotspots
       }
       imageMappingWidget.updateAttributes(updating, function (err) {
            if(err){console.log(err);}
        });

the structure of inlinehotspots in Mongo is now:

"inlinehotspots" : [ [ { "x" : "188", "y" : "375", "product" : { "id" : ObjectId("54522c78c79bdbe0718c17a1"), "currency" : null, "currency_was" : null, "name" : "Base take away-glaskop, M", "name_was" : "Base take away-glaskop, M", "brand" : "KeepCup", "brand_was" : "KeepCup", "category" : "Rum - Køkken - Køkkenservering", "category_was" : "Rum - Køkken - Køkkenservering", "price" : "200.00", "price_was" : "200.00", "image" : "http://www.rum21.se/bilder/artiklar/128516.jpg", "image_was" : "http://www.rum21.se/bilder/artiklar/128516.jpg", "elink" : "http://pdt.tradedoubler.com/click?a(2438311)p(210349)prod(1726873687)ttid(5)url(http%3A%2F%2Fwww.rum21.se%2Fdk%2Fartiklar%2Fbase-take-away-glaskop-m.html)", "elink_was" : "http://pdt.tradedoubler.com/click?a(2438311)p(210349)prod(1726873687)ttid(5)url(http%3A%2F%2Fwww.rum21.se%2Fdk%2Fartiklar%2Fbase-take-away-glaskop-m.html)", "published" : null, "published_was" : null, "createDate" : "2014-10-30T13:17:53.017+01:00", "createDate_was" : "2014-10-30T13:17:53.017+01:00", "updateDate" : null, "updateDate_was" : null, "global" : false, "global_was" : false, "uploadedImage" : false, "uploadedImage_was" : false, "deliveryCost" : "", "deliveryCost_was" : "", "description" : null, "description_was" : null, "stock" : "", "stock_was" : "", "retailer" : "Room21.dk", "retailer_was" : "Room21.dk", "retailerId" : null, "retailerId_was" : null, "disabled" : false, "disabled_was" : false, "id_was" : ObjectId("54522c78c79bdbe0718c17a1"), "userId" : null, "userId_was" : null, "__finders__" : {  } }, "imgx" : "20", "imgy" : "262", "h" : "394", "w" : "701", "hotspotid" : "pfmq46jy61415914133997", "yfromImage" : "113", "xfromImage" : "168", "fromid" : "544d00c0c9daea1a0300000c" } ] ] 

when I get that out from another request then I end up with (below just shows structure, not actually the same inlinehotspots. 

"inlinehotspots": [
          {
            "0": {
              "x": "380",
              "y": "397",
              "product": {
                "id": "54522c78c79bdbe0718c17a1",
                "currency": null,
                "currency_was": null,
                "name": "Base take away-glaskop, M",
                "name_was": "Base take away-glaskop, M",
                "brand": "KeepCup",
                "brand_was": "KeepCup",
                "category": "Rum - Køkken - Køkkenservering",
                "category_was": "Rum - Køkken - Køkkenservering",
                "price": "200.00",
                "price_was": "200.00",
                "image": "http://www.rum21.se/bilder/artiklar/128516.jpg",
                "image_was": "http://www.rum21.se/bilder/artiklar/128516.jpg",
                "elink": "http://pdt.tradedoubler.com/click?a(2438311)p(210349)prod(1726873687)ttid(5)url(http%3A%2F%2Fwww.rum21.se%2Fdk%2Fartiklar%2Fbase-take-away-glaskop-m.html)",
                "elink_was": "http://pdt.tradedoubler.com/click?a(2438311)p(210349)prod(1726873687)ttid(5)url(http%3A%2F%2Fwww.rum21.se%2Fdk%2Fartiklar%2Fbase-take-away-glaskop-m.html)",
                "published": null,
                "published_was": null,
                "createDate": "2014-10-30T13:17:53.017+01:00",
                "createDate_was": "2014-10-30T13:17:53.017+01:00",
                "updateDate": null,
                "updateDate_was": null,
                "global": false,
                "global_was": false,
                "uploadedImage": false,
                "uploadedImage_was": false,
                "deliveryCost": "",
                "deliveryCost_was": "",
                "description": null,
                "description_was": null,
                "stock": "",
                "stock_was": "",
                "retailer": "Room21.dk",
                "retailer_was": "Room21.dk",
                "retailerId": null,
                "retailerId_was": null,
                "disabled": false,
                "disabled_was": false,
                "id_was": "54522c78c79bdbe0718c17a1",
                "userId": null,
                "userId_was": null,
                "__finders__": {}
              },
              "imgx": "20",
              "imgy": "262",
              "h": "394",
              "w": "701",
              "hotspotid": "k0qf72jw71415958263443",
              "yfromImage": "135",
              "xfromImage": "360",
              "fromid": "544d00c0c9daea1a0300000c"
            },
            "id": 1
          }

ok so anyway there is probably a misunderstanding on my part, but it also seems like this should be a bug. 

So for the short term, how do I go ahead and make something an array in the schema in such a way that my mongodb has 

"inlinehotspots" : [ { "x" : "188", "y" : "375", "product" : { "id" : ObjectId("54522c78c79bdbe0718c17a1"), "currency" : null, "currency_was" : null, "name" : "Base take away-glaskop, M", "name_was" : "Base take away-glaskop, M", "brand" : "KeepCup", "brand_was" : "KeepCup", "category" : "Rum - Køkken - Køkkenservering", "category_was" : "Rum - Køkken - Køkkenservering", "price" : "200.00", "price_was" : "200.00", "image" : "http://www.rum21.se/bilder/artiklar/128516.jpg", "image_was" : "http://www.rum21.se/bilder/artiklar/128516.jpg", "elink" : "http://pdt.tradedoubler.com/click?a(2438311)p(210349)prod(1726873687)ttid(5)url(http%3A%2F%2Fwww.rum21.se%2Fdk%2Fartiklar%2Fbase-take-away-glaskop-m.html)", "elink_was" : "http://pdt.tradedoubler.com/click?a(2438311)p(210349)prod(1726873687)ttid(5)url(http%3A%2F%2Fwww.rum21.se%2Fdk%2Fartiklar%2Fbase-take-away-glaskop-m.html)", "published" : null, "published_was" : null, "createDate" : "2014-10-30T13:17:53.017+01:00", "createDate_was" : "2014-10-30T13:17:53.017+01:00", "updateDate" : null, "updateDate_was" : null, "global" : false, "global_was" : false, "uploadedImage" : false, "uploadedImage_was" : false, "deliveryCost" : "", "deliveryCost_was" : "", "description" : null, "description_was" : null, "stock" : "", "stock_was" : "", "retailer" : "Room21.dk", "retailer_was" : "Room21.dk", "retailerId" : null, "retailerId_was" : null, "disabled" : false, "disabled_was" : false, "id_was" : ObjectId("54522c78c79bdbe0718c17a1"), "userId" : null, "userId_was" : null, "__finders__" : {  } }, "imgx" : "20", "imgy" : "262", "h" : "394", "w" : "701", "hotspotid" : "pfmq46jy61415914133997", "yfromImage" : "113", "xfromImage" : "168", "fromid" : "544d00c0c9daea1a0300000c" } ] 

I've taken liberties in not putting everything in here, but just tried to get stuff that I figured was relevant, so as not to make a big code dump.

**Comment by 1602** [comment]
Please add test case and reopen issue if this is still the case.
