### ISSUE TITLE
can't npm install

### ISSUE THREAD

**Issue by mpress** [jugglingdb/mongodb-adapter#34]
Using node  v0.12.5
invoking
>npm install jugglingdb-mongodb --save

results in the following output:
>npm WARN package.json slm-test@1.0.0 No repository field.
>npm WARN package.json slm-test@1.0.0 No README data
>/
>\> kerberos@0.0.15 install /Users/user/Documents/xenobe/intelliJ/slm-test/node_modules/jugglingdb->mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
>\> (node-gyp rebuild) || (exit 0)
>
>  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
>  CXX(target) Release/obj.target/kerberos/lib/worker.o
>  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
>../lib/kerberosgss.c:509:13: warning: implicit declaration of function >'gss_acquire_cred_impersonate_name' is
>     invalid in C99 [-Wimplicit-function-declaration]
>        maj_stat = gss_acquire_cred_impersonate_name(&min_stat,
>                   ^
>1 warning generated.
>  CC(target) Release/obj.target/kerberos/lib/base64.o
>  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
>  SOLINK_MODULE(target) Release/kerberos.node
>ld: library not found for -lgcc_s.10.5
>clang: error: linker command failed with exit code 1 (use -v to see invocation)
>make: *** [Release/kerberos.node] Error 1
>gyp ERR! build error
>gyp ERR! stack Error: `make` failed with exit code: 2
>gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node->gyp/lib/build.js:269:23)
>gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
>gyp ERR! System Darwin 14.5.0
>gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" >"rebuild"
>gyp ERR! cwd /Users/user/Documents/xenobe/intelliJ/slm-test/node_modules/jugglingdb->mongodb/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
>gyp ERR! node -v v0.12.5
>gyp ERR! node-gyp -v v2.0.1
>gyp ERR! not ok
>jugglingdb-mongodb@0.0.3 node_modules/jugglingdb-mongodb
>└── mongodb@2.0.45 (es6-promise@2.1.1, readable-stream@1.0.31, mongodb-core@1.2.14)

**Comment by 1602** [comment]
It is working fine now on node versions 0.x,4,5,6
